spring:
  jpa:
    defer-datasource-initialization: true

# Or to totally disable DataSource:
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
